schema:
  - http://localhost:1337/v1/graphql:
      headers:
        x-hasura-admin-secret: nhost-admin-secret
generates:
  utils/__generated__/graphql.ts:
    documents:
      - './graphql/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
    config:
      fetcher:
        func: '../gql-fetcher#fetchData'
        isReactHook: false
  functions/_utils/__generated__/graphql-request.ts:
    documents:
      - 'functions/**/*.graphql'
      - 'functions/**/*.gql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-graphql-request'
