-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."matters" add column "status" Text
--  not null default 'pending';
